version: '3.5'

services:
  api:
    build: ./
    ports:
      - 80:8000

    command: bash run.sh

    networks:
      - app-net
    volumes:
      - ./:/home/
      
      





networks:
  app-net:

